"use client";

import React from 'react';
import LegalLayout from '../../legal-layout';

export default function ShippingPage() {
   return (
      <LegalLayout title="Pricing & Shipping">
         <div className="space-y-12 text-black/80">
            <p className="text-xl font-medium leading-relaxed">
               This transparency brief outlines the pricing structures and digital delivery protocols for the Diney Sovereign network.
            </p>

            <section className="space-y-6">
               <h2 className="text-2xl font-bold uppercase tracking-tight">1. Subscription Pricing</h2>
               <p className="leading-relaxed">
                  Diney provides tiered subscription plans (Standard, Plus, and Pro). Current rates are transparently displayed on our primary website. All plans are subject to recurring billing unless otherwise specified.
               </p>
            </section>

            <section className="space-y-6">
               <h2 className="text-2xl font-bold uppercase tracking-tight">2. Zero Physical Shipping</h2>
               <p className="leading-relaxed">
                  Diney is a 100% Software-as-a-Service (SaaS) provider. We do not ship physical products, hardware, or printed QR menus. Users are responsible for printing and displaying the digital QR codes generated by the Service.
               </p>
            </section>

            <section className="space-y-6">
               <h2 className="text-2xl font-bold uppercase tracking-tight">3. Digital Delivery Protocol</h2>
               <p className="leading-relaxed">
                  Access to the Diney dashboard and the activation of Sovereign Nodes is delivered electronically via the provided account email and dashboard portal immediately upon successful payment confirmation.
               </p>
            </section>

            <section className="space-y-6">
               <h2 className="text-2xl font-bold uppercase tracking-tight">4. Fees & Taxes</h2>
               <p className="leading-relaxed">
                  All listed prices are exclusive of GST or other regional taxes, which will be added at checkout as per statutory requirements.
               </p>
            </section>

            <div className="pt-12 border-t border-black/5 italic text-black/40">
               Last Updated: March 17, 2026
            </div>
         </div>
      </LegalLayout>
   );
}
